import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  designSidebar: [{type: 'autogenerated', dirName: "GameDesign"}],
  godotSidebar: [{type: 'autogenerated', dirName: "GameDev/Godot"}],
  unitySidebar: [{type: 'autogenerated', dirName: "GameDev/Unity"}],
  unrealSidebar: [{type: 'autogenerated', dirName: "GameDev/UnrealEngine"}],
  gamedevMiscSidebar: [{type: 'category', label: "Cocos", items:[
    {type: 'autogenerated', dirName: "GameDev/Cocos"},
  ],}],
  miscSidebar: [{type: 'autogenerated', dirName: "Misc"}],
  homelabSidebar: [{type: 'autogenerated', dirName: "Homelab"}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
